# fly.toml app configuration file generated for lini-api-production on 2024-06-11T20:19:25+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'lini-api-production'
primary_region = 'ams'
swap_size_mb = 2048

[build]

[deploy]
release_command = 'npx prisma migrate deploy'

[env]
PORT = '3000'

[http_service]
internal_port = 3000
force_https = true
auto_stop_machines = true
auto_start_machines = true
min_machines_running = 0
processes = ['app']

[[vm]]
size = 'shared-cpu-1x'
