name: "Deploy Server"

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3 # needed until 18 becomes the default
        with:
          node-version: 18
          cache: yarn
      - name: Install dependencies
        run: yarn install --frozen-lockfile
        working-directory: ./apps/server
      - name: Generate Prisma Client
        working-directory: ./apps/server
        run: yarn prisma generate
      - name: Build
        working-directory: ./apps/server
        run: yarn build
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy --remote-only ./apps/server/build
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
